### ISSUE TITLE
Audio Visualizer

### ISSUE THREAD

**Issue by Swan** [Quaver/Wobble#4]
There should be some sort of customizable visualizer developed at the framework level.

**Comment by percyqaz** [comment]
You can pull waveform data from BASS with 
`Bass.ChannelGetData(<ID>, <OUTPUT ARRAY>, (int)DataFlags.FFT2048)`
and may find the algorithm [here](https://www.codeproject.com/Articles/797537/Making-an-Audio-Spectrum-analyzer-with-Bass-dll-Cs) useful for building a visualiser
