### ISSUE TITLE
Update MonoGame.Dependencies

### ISSUE THREAD

**Issue by nobbele** [Quaver/Wobble#82]
Updating MonoGame.Dependencies to use a newer SDL fixes issues such as key repeat on linux, I made a fork [here](https://github.com/nobbele/MonoGame.Dependencies/tree/master) but I couldn't seem to integrate it into the [MonoGame fork by Quaver](https://github.com/Quaver/MonoGame/tree/fa14c789cb75e70c859cf79b877a11939c1a4dce) because it uses some old commit or something and Quaver won't compile with the newer ones

**Comment by YaLTeR** [comment]
+1, new SDL also fixes a Wayland crash.
